# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jwoffindin-foreigner}
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John woffindin"]
  s.date = %q{2011-01-06}
  s.description = %q{Allows you to add foreign keys to your migrations and enforce them}
  s.email = %q{john.woffindin@sla-mobile.com.my}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/foreigner.rb",
    "lib/foreigner/connection_adapters/abstract/schema_definitions.rb",
    "lib/foreigner/connection_adapters/abstract/schema_statements.rb",
    "lib/foreigner/connection_adapters/mysql_adapter.rb",
    "lib/foreigner/connection_adapters/postgresql_adapter.rb",
    "lib/foreigner/connection_adapters/sqlite3_adapter.rb",
    "lib/foreigner/schema_dumper.rb",
    "lib/foreigner/semantics/sql_2003.rb",
    "spec/adapter_helper.rb",
    "spec/factory_helper.rb",
    "spec/mysql/schema_extractor_spec.rb",
    "spec/mysql/schema_spec.rb",
    "spec/mysql/semantics_spec.rb",
    "spec/postgresql/schema_extractor_spec.rb",
    "spec/postgresql/schema_spec.rb",
    "spec/postgresql/semantics_spec.rb",
    "spec/schema_dumper_spec.rb",
    "spec/spec_helper.rb",
    "spec/sqlite3/schema_spec.rb",
    "tasks/foreigner_tasks.rake"
  ]
  s.homepage = %q{http://github.com/jwoffindin/foreigner}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Foreign keys for Rails migrations for PostgreSQL, MySQL and Sqlite3. Based on sparkfly-foreigner}
  s.test_files = [
    "spec/adapter_helper.rb",
    "spec/factory_helper.rb",
    "spec/mysql/schema_extractor_spec.rb",
    "spec/mysql/schema_spec.rb",
    "spec/mysql/semantics_spec.rb",
    "spec/postgresql/schema_extractor_spec.rb",
    "spec/postgresql/schema_spec.rb",
    "spec/postgresql/semantics_spec.rb",
    "spec/schema_dumper_spec.rb",
    "spec/spec_helper.rb",
    "spec/sqlite3/schema_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

